git:
  pagers:
    - colorArg: always
      pager: delta --paging=never --line-numbers --light --syntax-theme=everforest-light-medium
gui:
  theme:
    activeBorderColor:
      - "#2e7099"
      - bold
    inactiveBorderColor:
      - "#829181"
    defaultFgColor:
      - "#5c6a72"
    optionsTextColor:
      - "#2c7459"
    selectedLineBgColor:
      - "#f4f0d9"
    selectedRangeBgColor:
      - "#eaedc8"
    unstagedChangesColor:
      - "#ad3b4a"
    cherryPickedCommitBgColor:
      - "#f0f1d2"
    cherryPickedCommitFgColor:
      - "#47661b"
    searchingActiveBorderColor:
      - "#8c5a00"
      - bold
  authorColors:
    "*": "#5c6a72"
    "default": "#5c6a72"
    "A": "#2e7099"
    "B": "#2c7459"
    "C": "#47661b"
    "D": "#8c5a00"
    "E": "#9a5200"
    "F": "#8f537f"
    "G": "#ad3b4a"
    "H": "#708089"
