# Quiet Light for Kitty
# Adapted from onecrayon/theme-quietlight-vsc.

foreground #333333
background #f5f5f5
selection_foreground #333333
selection_background #c1f5b0

cursor #aaaaaa
cursor_text_color #f5f5f5
url_color #4b83cd

active_border_color #4b83cd
inactive_border_color #dcdcdc
bell_border_color #aa3731
visual_bell_color none

wayland_titlebar_color #f5f5f5
macos_titlebar_color #f5f5f5

active_tab_foreground #ffffff
active_tab_background #4b83cd
inactive_tab_foreground #777777
inactive_tab_background #e0e9f6
tab_bar_background #f2f2f2

mark1_foreground #333333
mark1_background #c1f5b0
mark2_foreground #ffffff
mark2_background #4b83cd
mark3_foreground #ffffff
mark3_background #448c27

color0 #333333
color8 #777777
color1 #aa3731
color9 #aa3731
color2 #448c27
color10 #448c27
color3 #ab6526
color11 #ab6526
color4 #4b83cd
color12 #4b83cd
color5 #7a3e9d
color13 #7a3e9d
color6 #4ec1e5
color14 #4ec1e5
color7 #f5f5f5
color15 #ffffff
