# vim:ft=kitty

## name: Quiet Light
## author: Kitty Quiet Light Theme Contributors
## license: MIT
## upstream: https://github.com/mni/kitty-quiet-light-theme/raw/main/quiet-light.conf
## blurb: A light color theme inspired by the VSCode Quiet Light theme, featuring warm neutral tones and a carefully crafted ANSI palette optimized for terminal readability.

# The basic colors

foreground                      #333333
background                      #F5F5F5
selection_foreground            #333333
selection_background            #C9D0D9

# Cursor colors

cursor                          #54494B
cursor_text_color               #F5F5F5

# URL underline color when hovering with mouse

url_color                       #4B69C6

# Kitty window border colors and terminal bell colors

active_border_color             #705697
inactive_border_color           #C9D0D9
bell_border_color               #AA3731
visual_bell_color               none

# OS Window titlebar colors

wayland_titlebar_color          #F5F5F5
macos_titlebar_color            #F5F5F5

# Tab bar colors

active_tab_foreground           #F5F5F5
active_tab_background           #705697
inactive_tab_foreground         #666666
inactive_tab_background         #E8E6E1
tab_bar_background              #E8E6E1

# Colors for marks (marked text in the terminal)

mark1_foreground                #F5F5F5
mark1_background                #4B69C6
mark2_foreground                #F5F5F5
mark2_background                #7A3E9D
mark3_foreground                #F5F5F5
mark3_background                #007D6F

# The basic 16 colors

# black
color0                          #333333
color8                          #666666

# red
color1                          #AA3731
color9                          #C8413A

# green
color2                          #357B20
color10                         #469428

# yellow
color3                          #8A5221
color11                         #AD6B2A

# blue
color4                          #4B69C6
color12                         #5A7ED8

# magenta
color5                          #7A3E9D
color13                         #955AB5

# cyan
color6                          #007D6F
color14                         #009A8A

# white
color7                          #CCC9C2
color15                         #EEEAE4
