# vim:ft=kitty

## name: Tokyo Night Day
## license: MIT
## upstream: https://github.com/folke/tokyonight.nvim
## blurb: Light variant of the Tokyo Night palette — cool blue text on a soft slate-blue background.

# The basic colors

foreground                      #3760bf
background                      #e1e2e7
selection_foreground            #3760bf
selection_background            #c4c8da

# Cursor colors

cursor                          #3760bf
cursor_text_color               #e1e2e7

# URL underline color when hovering with mouse

url_color                       #2e7de9

# Kitty window border colors and terminal bell colors

active_border_color             #2e7de9
inactive_border_color           #a8aecb
bell_border_color               #f52a65
visual_bell_color               none

# OS Window titlebar colors

wayland_titlebar_color          #e1e2e7
macos_titlebar_color            #e1e2e7

# Tab bar colors

active_tab_foreground           #e1e2e7
active_tab_background           #2e7de9
inactive_tab_foreground         #6172b0
inactive_tab_background         #d0d5e3
tab_bar_background              #d0d5e3

# Colors for marks (marked text in the terminal)

mark1_foreground                #e1e2e7
mark1_background                #2e7de9
mark2_foreground                #e1e2e7
mark2_background                #9854f1
mark3_foreground                #e1e2e7
mark3_background                #118c74

# The basic 16 colors

# black
color0                          #b4b5b9
color8                          #a1a6c5

# red
color1                          #f52a65
color9                          #ff4774

# green
color2                          #587539
color10                         #6a8a3f

# yellow
color3                          #8c6c3e
color11                         #b15c00

# blue
color4                          #2e7de9
color12                         #4094f7

# magenta
color5                          #9854f1
color13                         #7847bd

# cyan
color6                          #007197
color14                         #118c74

# white
color7                          #6172b0
color15                         #3760bf
